[phases.setup]
nixPkgs = ["php82", "php82Extensions.mbstring", "php82Extensions.pdo_mysql"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction"
]

[phases.build]
cmds = [
    "mkdir -p storage/framework/{sessions,views,cache}",
    "mkdir -p storage/logs",
    "chmod -R 775 storage bootstrap/cache"
]

[start]
cmd = "bash deploy.sh"
