[phases.setup]
nixPkgs = ["php82", "php82Extensions.mbstring", "php82Extensions.curl", "php82Extensions.dom", "php82Extensions.simplexml", "php82Extensions.pdo", "php82Extensions.pdo_mysql"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader"
]

[phases.build]
cmds = [
    "php artisan config:cache",
    "php artisan route:cache",
    "chmod -R 755 storage bootstrap/cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"
